import * as vscode from 'vscode';

/**
 * Represents a diagnostics generated by proposeTestFiles.
 */
export interface TestFileDiagnosticResult {
    /** Diagnostic message. */
    message: string;

    /** File path that triggered diagnostic message, if any. */
    sourceFile: vscode.Uri | null;

    /** Identifier for diagnostic kind. */
    kind: TestFileDiagnosticKind
}

export enum TestFileDiagnosticKind {
    fileNotInSourcesFolder
};
